name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: ["closed"]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build_and_publish:
    
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      
      # Check out the repository (basically downloads the source code)
      - uses: actions/checkout@v3

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Create Artifact
        run: |
          mkdir ${{ matrix.os }}-release
          cp build/Mandelbrot* ${{ matrix.os }}-release/
      
      - name: ZIP Artifact
        run: |
          zip -r ${{ matrix.os }}.zip ${{ matrix.os }}-release/
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: ${{ matrix.os }}
          path: ${{ matrix.os }}.zip
          
#      - name: Create Release
#        uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "latest"
#          prerelease: true
#          title: "Development Build"
#          files: |
#            build/Mandelbrot*

  release:
    name: "Prelease"
    needs: build_and_publish
    runs-on: ubuntu-latest
    steps:
      # We don't need the repo, grab all artifacts from the build stage
      # The plugin puts each artifact in a folder of `artifactname`
      - uses: actions/download-artifact@v2
      
      - name: Display fetched artifacts
        run: ls -R
        
#      - name: ZIP fetched artifacts
#        run: |
#          for i in */; do zip -r "${i%/}.zip" "$i"; done
      
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ubuntu-latest/ubuntu-latest.zip
            macos-latest/macos-latest.zip
#            ubuntu-latest-release.zip
#            macos-latest-release.zip
#            windows-latest-release
